version: 0.1
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run test:ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build s3://$S3_BUCKET --delete
artifacts:
  files:
    - "build/*"
  base-directory: "."
