version: 0.1
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run test:ci
  build:
    commands:
      - npm run build
      - echo Contents of where the build occured
      - ls -lart
      - echo Contents of build
      - ls -lart build
artifacts:
  files:
    - "**/*"
  base-directory: "build"
