version: 0.1
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run test:ci
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: "build"
